os: linux
dist: focal
language:
  python
python:
  - "3.8"
before_install:
  - sudo apt-get -y install python3-pip
  - sudo apt-get -y install python-dev graphviz libgraphviz-dev pkg-config
install:  
  - pip install coverage
  - pip install -r requirements.txt
script:
  - python manage.py test